[package]
name = "fc_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.9"
sha3 = "0.10.8"
twox-hash = "2.1.2"
xxhash-rust = { version = "=0.8.15", features = ["xxh3"] }
rusqlite = { version = "0.31", features = ["bundled"] }